### ISSUE TITLE
Magnetic declination

### ISSUE THREAD

**Issue by robertfausto** [GEUS-PROMICE/NEAD#1]
For the new version 3 AWS has a compass, so AWS orientation is also a measured parameter. The compass measures xxx degrees from magnetic north. So the header should include "magnetic declination"

**Comment by mankoff** [comment]
This is a PROMICE-data column issue and the generic NEAD format does not need to be adjusted for this. The PROMICE NEAD header template does need to be adjusted for this new sensors & variable. I'm closing here and moving to https://github.com/GEUS-PROMICE/PROMICE-AWS-processing because the PROMICE-AWS-processing pipeline needs to handle this new variable. That means:

+ Picking a short, long, and standard name https://github.com/GEUS-PROMICE/PROMICE-AWS-processing/issues/2
+ Writing code to use this variable to adjust other variables https://github.com/GEUS-PROMICE/PROMICE-AWS-processing/issues/3
