### ISSUE TITLE
timezone improvement

### ISSUE THREAD

**Issue by iosifescu** [GEUS-PROMICE/NEAD#6]
Let's discuss the following options for better addressing the timezone:

1. modify the tz key to timezone (it is more explicit and therefore better understandable). 
The values remain numeric, however positive numbers can be expressed with or without the plus sign, E.g. if the timestamps are expressed in UTC+1, then both timezone = 1 or timezone = +1 are correct. Default remains 0 (Zulu/UTC).

2. eliminate the timezone key completely, and define that if the timestamp is not UTC then the add_value for timestamp just exist

I prefer option 1 (because it is more logical for people).

**Comment by iosifescu** [comment]
In addition, option 2 would make it quite hard to understand and separate timezone adjustments from clock shifts/calibrations (in case people might chose to provide clock calibrations). So option 2 was a bad idea...

**Comment by ghost** [comment]
Reopening because timezones are quirky things that can't be represented by one number, so it's more than how to name this field. Why not just require all time stamps to be UTC and remove the timezone field entirely?

The only quirk of UTC is leap seconds and they are poorly supported by most non-astronomy time libraries. If leaps seconds are too much trouble, then posix time ignores them. But what happens when a time series has a record for 31-12-2016 23:59:60? Is the ambition for NEAD to be general enough to accommodate all kinds of environmental datasets?

If the intention really is to deal with timezones, then this field should contain the name of the timezone from the Olsen database so that implementations can use existing libraries to take care of the details. In python [pytz](https://pypi.org/project/pytz/) plays well with pandas. The leap seconds problem still applies.

**Comment by mankoff** [comment]
We're getting into the difference between the NEAD format and a NEAD-reader. The format will use `timezone` instead of `tz`. 

Separate discussion: What is the list of valid values for that key. I agree with @citterio that we can process more than single digits. I suggest that valid entries include a single digit (UTC offset), or standard strings from the Olson database.

For now, my https://github.com/GEUS-PROMICE/pyNEAD parser only handles single digits, but I'll add full tz string parsing at some point if needed.

**Comment by iosifescu** [comment]
> Why not just require all time stamps to be UTC and remove the timezone field entirely?

The idea is to be able to obtain all time stamps in UTC. Removing would be one option, but we get again into the lengthy discussions about enforcing international SI units for all fields. We have already decided to allow other units (like Celsius instead of Kelvin), if transformations are defined in order to allow a software to obtain the international units if needed. The NEAD format includes add_value and scale_factor (for fields) for this purpose. But the timestamp is a special kind of field. So timestamp being special, deserves special consideration in the [METADATA] section. 

> The only quirk of UTC is leap seconds and they are poorly supported by most non-astronomy time libraries. If leaps seconds are too much trouble, then posix time ignores them. But what happens when a time series has a record for 31-12-2016 23:59:60? Is the ambition for NEAD to be general enough to accommodate all kinds of environmental datasets?

Yes (as much as this goal can be achieved).

> If the intention really is to deal with timezones, then this field should contain the name of the timezone from the Olsen database so that implementations can use existing libraries to take care of the details. In python [pytz](https://pypi.org/project/pytz/) plays well with pandas. The leap seconds problem still applies.
> We're getting into the difference between the NEAD format and a NEAD-reader. The format will use `timezone` instead of `tz`.

Exactly. This format change was only about tz (old) -> timezone (new)

> I suggest that valid entries include a single digit (UTC offset), or standard strings from the Olson database.

OK for me, thanks.
